# Generated by Django 6.0 on 2026-01-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Technology', 'Technology'), ('Education', 'Education'), ('Science', 'Science'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
