# Generated by Django 6.0 on 2026-01-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Technology', 'Technology'), ('Education', 'Education'), ('Science', 'Science'), ('General', 'General'), ('love', 'love'), ('Biography', 'Biography'), ('horror', 'horror'), ('romantic', 'romantic'), ('Self-help', 'Self-help'), ('storytelling', 'storytelling'), ('children', 'children'), ('competative', 'competative'), ('psychology', 'psychology'), ('Motivated', 'Motivated'), ('Fantasy', 'Fantasy'), ('Novels', 'Novels'), ('History', 'History'), ('Biography', 'Biography'), ('Comics', 'Comics'), ('Self-help', 'Self-help'), ('Poetry', 'Poetry'), ('Thriller/Mystery', 'Thriller/Mystery')], default='General', max_length=50),
        ),
    ]
