# Generated by Django 6.0 on 2026-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Fiction', 'Fiction'), ('Non fiction', 'Non fiction'), ('Technology', 'Technology'), ('Education', 'Education'), ('Science', 'Science'), ('General', 'General'), ('Love', 'Love'), ('Biography', 'Biography'), ('Horror', 'Horror'), ('Romantic', 'Romantic'), ('Self-help', 'Self-help'), ('Storytelling', 'Storytelling'), ('Children', 'Children'), ('Competitive', 'Competitive'), ('Psychology', 'Psychology'), ('Motivated', 'Motivated'), ('Fantasy', 'Fantasy'), ('Novels', 'Novels'), ('History', 'History'), ('Biography', 'Biography'), ('Comics', 'Comics'), ('Self-help', 'Self-help'), ('Poetry', 'Poetry'), ('Thriller/Mystery', 'Thriller/Mystery')], default='General', max_length=50),
        ),
    ]
